services:
  - type: static_site
    name: ia-frontend-prod
    branch: prod-single-dashboard
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_BACKEND_URL
        value: https://ia-backend-prod.onrender.com

  - type: static_site
    name: ia-frontend-qa
    branch: qa-multipage
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_BACKEND_URL
        value: https://ia-backend-qa.onrender.com

  - type: static_site
    name: ia-frontend-staging
    branch: staging-multipage
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_BACKEND_URL
        value: https://ia-backend-staging.onrender.com
